// tools/measure-resolution.ts — how much of the corpus the parser + current dictionary resolve.
//
// Parses every ingredient line of data/source/recipes-recepten2.json with the dictionary built
// from data/*.json (data/ingredients.json when present, otherwise an empty ingredient list),
// prints the resolved percentage (unique lines and all lines), the prep-note coverage and the
// unresolved name parts by frequency, and writes docs/measure-resolution.md (same report).
//
// Run:   node --experimental-strip-types tools/measure-resolution.ts
// Node 22 type-stripping rules apply: type-only syntax only, plain ESM, no enums/namespaces.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import process from 'node:process';
import { loadDictionary, type Dictionary } from '../src/domain/dictionary.ts';
import { parseLine } from '../src/domain/parser.ts';
import { renderLine } from '../src/domain/render.ts';
import { buildNameParts, readDictionaryData, sourceLines, type NamePart } from './build-dictionary-seed.ts';

export interface ResolutionReport {
  ingredients: number;
  lines: number;
  uniqueLines: number;
  headers: number;
  resolvedAll: number;
  resolvedUnique: number;
  withQtyUnique: number;
  withUnitUnique: number;
  prepNotes: number;
  prepTranslated: number;
  lowConfidence: number;
  unresolved: NamePart[];
  /** A few resolved lines rendered NL / EN, as a smoke test of the pipeline. */
  samples: { raw: string; nl: string; en: string }[];
}

export function measureResolution(lines: readonly string[], dict: Dictionary): ResolutionReport {
  const unique = [...new Set(lines.map((l) => l.trim()).filter(Boolean))];
  let headers = 0;
  let resolvedAll = 0;
  let resolvedUnique = 0;
  let withQtyUnique = 0;
  let withUnitUnique = 0;
  let lowConfidence = 0;
  const prepNotes = new Map<string, boolean>();
  const samples: ResolutionReport['samples'] = [];
  const unresolvedLines: string[] = [];

  for (const raw of lines) {
    const line = parseLine(raw, dict, 'nl');
    if (line.kind !== 'header' && line.ing) resolvedAll++;
  }
  for (const raw of unique) {
    const line = parseLine(raw, dict, 'nl');
    if (line.kind === 'header') {
      headers++;
      continue;
    }
    if (line.qty) withQtyUnique++;
    if (line.unit) withUnitUnique++;
    if ((line.confidence ?? 0) < 0.6) lowConfidence++;
    for (const m of raw.matchAll(/\[([^\]]*)\]/g)) {
      const note = (m[1] ?? '').trim();
      if (note && !prepNotes.has(note)) prepNotes.set(note, dict.prepFor(note).en !== undefined);
    }
    if (line.ing) {
      resolvedUnique++;
      if (samples.length < 12 && (line.prep || line.alt || line.part || line.qual?.length)) {
        samples.push({ raw, nl: renderLine(line, dict, 'nl'), en: renderLine(line, dict, 'en') });
      }
    } else {
      unresolvedLines.push(raw);
    }
  }
  const unresolved = buildNameParts(unresolvedLines, dict);
  return {
    ingredients: dict.ingredients.length,
    lines: lines.length,
    uniqueLines: unique.length,
    headers,
    resolvedAll,
    resolvedUnique,
    withQtyUnique,
    withUnitUnique,
    prepNotes: prepNotes.size,
    prepTranslated: [...prepNotes.values()].filter(Boolean).length,
    lowConfidence,
    unresolved,
    samples,
  };
}

function pct(part: number, whole: number): string {
  return whole === 0 ? '0.0%' : `${((100 * part) / whole).toFixed(1)}%`;
}

export function renderMarkdown(r: ResolutionReport): string {
  const bodyUnique = r.uniqueLines - r.headers;
  const out: string[] = [];
  out.push('# Parser resolution over the corpus');
  out.push('');
  out.push('Generated by `node --experimental-strip-types tools/measure-resolution.ts` over');
  out.push('`data/source/recipes-recepten2.json` with the dictionary in `data/*.json`. Re-run to reproduce.');
  out.push('');
  out.push('## Totals');
  out.push('');
  out.push(`- Dictionary ingredients: **${r.ingredients}**`);
  out.push(`- Lines: **${r.lines}** (unique: ${r.uniqueLines}, of which headers: ${r.headers})`);
  out.push(`- Resolved (ingredient id found): **${r.resolvedUnique} / ${bodyUnique} unique = ${pct(r.resolvedUnique, bodyUnique)}**, ${r.resolvedAll} / ${r.lines} all lines = ${pct(r.resolvedAll, r.lines)}`);
  out.push(`- Unique lines with a quantity: ${r.withQtyUnique} (${pct(r.withQtyUnique, bodyUnique)}); with a unit: ${r.withUnitUnique} (${pct(r.withUnitUnique, bodyUnique)})`);
  out.push(`- Prep notes \`[…]\`: ${r.prepTranslated} / ${r.prepNotes} distinct translated (${pct(r.prepTranslated, r.prepNotes)})`);
  out.push(`- Unique lines with confidence < 0.6: ${r.lowConfidence}`);
  out.push('');
  out.push(`## Unresolved name parts (${r.unresolved.length}), most frequent first`);
  out.push('');
  out.push('| # | Name part | Lines | Qualifiers seen | Units seen | Example |');
  out.push('|---:|---|---:|---|---|---|');
  r.unresolved.slice(0, 400).forEach((p, i) => {
    out.push(`| ${i + 1} | ${p.name} | ${p.count} | ${p.qual.join(', ')} | ${p.units.join(', ')} | \`${p.examples[0] ?? ''}\` |`);
  });
  if (r.unresolved.length > 400) out.push(`| … | (${r.unresolved.length - 400} more) | | | | |`);
  out.push('');
  if (r.samples.length) {
    out.push('## Rendered samples (NL / EN)');
    out.push('');
    for (const s of r.samples) out.push(`- \`${s.raw}\` → ${s.nl} / ${s.en}`);
    out.push('');
  }
  return out.join('\n');
}

function main(): void {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const dict = loadDictionary(readDictionaryData(root, true));
  const lines = sourceLines(root);
  const report = measureResolution(lines, dict);
  const md = renderMarkdown(report);
  const docsDir = join(root, 'docs');
  mkdirSync(docsDir, { recursive: true });
  writeFileSync(join(docsDir, 'measure-resolution.md'), md, 'utf8');
  const bodyUnique = report.uniqueLines - report.headers;
  console.log(`resolved: ${report.resolvedUnique}/${bodyUnique} unique lines (${pct(report.resolvedUnique, bodyUnique)}), ${report.resolvedAll}/${report.lines} all (${pct(report.resolvedAll, report.lines)}); ingredients in dictionary: ${report.ingredients}`);
  console.log(`prep notes translated: ${report.prepTranslated}/${report.prepNotes} (${pct(report.prepTranslated, report.prepNotes)}); low-confidence unique lines: ${report.lowConfidence}`);
  console.log(`unresolved name parts: ${report.unresolved.length}; top 20:`);
  for (const p of report.unresolved.slice(0, 20)) console.log(`  ${String(p.count).padStart(4)}  ${p.name}`);
  console.log('report written to docs/measure-resolution.md');
}

const invokedDirectly =
  typeof process.argv[1] === 'string' && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) main();
